/**
 * Class names for various state classes. Valid symbols, but not declared in base game scripts.
 */
class CPlayerStateApproachTheVehicle extends ApproachTheVehicle {}
class CPlayerStateDismountBoat extends DismountBoat     {}
class CPlayerStateDismountTheVehicle extends DismountTheVehicle {}
class CPlayerStateTraverseExploration extends TraverseExploration {}
class CR4PlayerStateCombat extends Combat {}
class CR4PlayerStateHorseRiding extends HorseRiding {}
class CR4PlayerStateMountBoat extends MountBoat {}
class CR4PlayerStateMountHorse extends MountHorse {}
class CR4PlayerStateSailing extends Sailing {}
class CR4PlayerStateSwimming extends Swimming {}
class CR4PlayerStateUnconscious extends Unconscious {}
class CR4PlayerStateUseGenericVehicle extends UseGenericVehicle {}
class CRiftEntityStateOpened extends Opened {}
class W3BoatSpawnerStateSpawnBoatLatentHack extends SpawnBoatLatentHack {}
class W3PlayerWitcherStateApproachInteractionState extends ApproachInteractionState {}
class W3PlayerWitcherStateCombatFists extends CombatFists {}
class W3PlayerWitcherStateCombatSilver extends CombatSilver {}
class W3PlayerWitcherStateCombatSteel extends CombatSteel {}
class W3PlayerWitcherStateMeditation extends Meditation {}
class W3PlayerWitcherStateMeditationWaiting extends MeditationWaiting {}
class W3ToxicCloudStateArmed extends Armed {}
class W3TutorialManagerUIHandlerStateAlchemy extends Alchemy {}
class W3TutorialManagerUIHandlerStateAlchemyMutagens extends AlchemyMutagens {}
class W3TutorialManagerUIHandlerStateArmorUpgrades extends ArmorUpgrades {}
class W3TutorialManagerUIHandlerStateBooks extends Books {}
class W3TutorialManagerUIHandlerStateCharDevMutagens extends CharDevMutagens {}
class W3TutorialManagerUIHandlerStateCharacterDevelopment extends CharacterDevelopment {}
class W3TutorialManagerUIHandlerStateContinentMap extends ContinentMap {}
class W3TutorialManagerUIHandlerStateCraftingBuy extends CraftingBuy {}
class W3TutorialManagerUIHandlerStateCraftingSet extends CraftingSet {}
class W3TutorialManagerUIHandlerStateDye extends Dye {}
class W3TutorialManagerUIHandlerStateFood extends Food {}
class W3TutorialManagerUIHandlerStateMutationsCanResearch extends MutationsCanResearch {}
class W3TutorialManagerUIHandlerStateMutationsEquippedAfter extends MutationsEquippedAfter {}
class W3TutorialManagerUIHandlerStateMutationsEquipping extends MutationsEquipping {}
class W3TutorialManagerUIHandlerStateMutationsUnlockedSkillSlot extends MutationsUnlockedSkillSlot {}
class W3TutorialManagerUIHandlerStateNewGeekpage extends NewGeekpage {}
class W3TutorialManagerUIHandlerStateOils extends Oils {}
class W3TutorialManagerUIHandlerStatePotions extends Potions {}
class W3TutorialManagerUIHandlerStateRecipeReading extends RecipeReading {}
class W3TutorialManagerUIHandlerStateRunes extends Runes {}
class W3TutorialManagerUIHandlerStateSecondPotionEquip extends SecondPotionEquip {}
class W3TutorialManagerUIHandlerStateSetItemsInfo extends SetItemsInfo {}
class W3TutorialManagerUIHandlerStateSetItemsUnlocked extends SetItemsUnlocked {}
class W3TutorialManagerUIHandlerStateShop extends Shop {}
class W3TutorialManagerUIHandlerStateSpecialAttacks extends SpecialAttacks {}
class W3YrdenEntityStateYrdenShock extends YrdenShock {}
