abstract class IActorConditionType {}
abstract class IBoidLairEntity {}
abstract class ICustomCameraPositionController {}
abstract class IGameSystem {}
abstract class IGameplayDLCMounter {}
abstract class IMoveSteeringCondition {}
abstract class IQuestCondition {}
abstract class IReactionAction {}
abstract class IReactionCondition {}
abstract class IScriptedFlash {}
abstract class ISerializable {}
abstract class ITexture {}
